### ISSUE TITLE
error code: ESRCH No such process (3)

### ISSUE THREAD

**Issue by Yarik900** [bernardladenthin/BitcoinAddressFinder#35]
When starting it gives the following error in the log:

[main] INFO  net.ladenthin.bitcoinaddressfinder.cli.Main - Find
Exception in thread "main" org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: ESRCH No such process (3)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
	at org.lmdbjava.Env$Builder.open(Env.java:495)
	at org.lmdbjava.Env$Builder.open(Env.java:512)
	at net.ladenthin.bitcoinaddressfinder.persistence.lmdb.LMDBPersistence.init(LMDBPersistence.java:113)
	at net.ladenthin.bitcoinaddressfinder.ConsumerJava.initLMDB(ConsumerJava.java:100)
	at net.ladenthin.bitcoinaddressfinder.Finder.startConsumer(Finder.java:79)
	at net.ladenthin.bitcoinaddressfinder.cli.Main.run(Main.java:86)
	at net.ladenthin.bitcoinaddressfinder.cli.Main.main(Main.java:73)

How to fix that?

**Comment by bernardladenthin** [comment]
Hi, can you give me more details about your machine / os?
